### ISSUE TITLE
[BUG] Proficiency Highlights Persisting

### ISSUE THREAD

**Issue by 9ryex5** [ZeroXNoxus/dark-mode-5e#1]
After enabling and disabling dark mode, ability scores with proficiency remain highlighted.
![image](https://user-images.githubusercontent.com/43207603/212541136-cff18ff6-e5a4-42b3-9d2d-373a63fda6b3.png)

**Comment by ZeroXNoxus** [comment]
Hello, the highlighted proficient saves and skills are highlighted to make it easier to see, as it sometimes can be a bit unclear while just looking at the numbers.
The feature is working as intended.

**Comment by 9ryex5** [comment]
Indeed, I thought the module was only making changes when dark theme was active. Thanks for the clarification.
