### ISSUE TITLE
Chat context menu is broken with Dark mode enabled

### ISSUE THREAD

**Issue by ChthonicKnight** [ZeroXNoxus/dark-mode-5e#11]
Chat context menu is broken with Dark mode enabled.
Can no longer right-click to open the chat context menu while Dark mode is active.

Example while disabled:
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/7c7add31-eeba-44de-b2ef-c4ceb3e45fa5)

**Comment by ZeroXNoxus** [comment]
This issue I can not reproduce. Maybe some other module causes this issue in conflict with dark mode?

3.0.1 chat with context menu (while dark mode is enabled):
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/29397572/405f7f96-9bbb-4b8c-85b1-3b2aed978100)

2.1.4 chat with context menu (while dark mode is enabled):
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/29397572/fbd011b4-24c7-435a-846d-67bf9efa785b)

I require more information (eg. FoundryVTT version, DnD 5th Edition version) and maybe a list of modules you have installed.

**Comment by ZeroXNoxus** [comment]
I have looked into this and found the issue. My method for changing the color of the chat lead to the z-index being messed up. Issue will be resolved in the next release!
