### ISSUE TITLE
Conflict with two modules that add Players section buttons.

### ISSUE THREAD

**Issue by ChthonicKnight** [ZeroXNoxus/dark-mode-5e#12]
Seems to have a minor conflict with Item Piles and Rest Recovery for 5e. Both of these modueles add a pressable button underneath the Players pane and the button is hard to read/see.
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/41a43ce3-b20a-41e7-8119-abefd80a98a2)

**Comment by ZeroXNoxus** [comment]
Fixed in next release, thanks for your contribution!

**Comment by ChthonicKnight** [comment]
Oddly enough not sure what changed for this but now it's showing black on black.
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/500a9cb8-31a4-430a-a8b2-cb28cb9442f7)

**Comment by ZeroXNoxus** [comment]
What Browser are you using?

**Comment by ChthonicKnight** [comment]
The foundry install

**Comment by ZeroXNoxus** [comment]
I don't know what you mean by "the foundry install". I need the web browser you are using to display foundry on. For Chrome, the buttons look like this:
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/29397572/20284852-7ffc-4988-9d2c-d30bfeb385ee)

This also works in Opera GX and Firefox.

**Comment by ChthonicKnight** [comment]
You can download the installed version here
https://foundryvtt.com/community/chobitscrazy/licenses (I guess this links to my profile)
It's the Download Software link on the Foundry Page.
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/d5f0fa1a-8ddd-4b64-a5b7-5b1c0b87c58d)

I have Firefox as well, if I connect with a user on that I get the same:
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/41b0dd57-7fcd-4766-b557-9360b039534c)

**Comment by ZeroXNoxus** [comment]
Ahhh, I see, the Desktop Application. I'll give it a look, I however haven't yet worked with this. I'll give you an update when I'm done!

**Comment by ZeroXNoxus** [comment]
> I have Firefox as well, if I connect with a user on that I get the same:

I have just downloaded Firefox to make sure this issue is present, but I don't get the same button style:
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/29397572/988ebd88-bcae-486b-b440-f515af72ded7)

I have now tested DnD 5th Edition 3.0.X and 2.1.4. Are you sure you have the current version of Dark Mode (2.0.3) installed?

**Comment by ChthonicKnight** [comment]
Let me double check

**Comment by ChthonicKnight** [comment]
Ah that was the issue! I saw it update but I guess it didn't go to .3

Thanks!

**Comment by ZeroXNoxus** [comment]
You're welcome, thanks for your contribution. Let me know If you have any other issues with Dark Mode!
Cheers!
