### ISSUE TITLE
Chat chages reverted in 2.0.3

### ISSUE THREAD

**Issue by ChthonicKnight** [ZeroXNoxus/dark-mode-5e#13]
Rolled back the code and seems the chat is working correctly.
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/52a5b08f-0985-4e18-8d89-d0af4a2f4bea)

Updated to 2.0.3 getting chats that aren't converting:
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/081dc9cc-f116-46d0-8362-cc68e401c920)

**Comment by ZeroXNoxus** [comment]
Fixed in next release.

**Comment by ChthonicKnight** [comment]
Looks like chat is good now, but character monitor is back to the original.
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/91696810-74b8-44f3-9665-b232e446f5d5)
