### ISSUE TITLE
Conflict with Automated Animations module

### ISSUE THREAD

**Issue by Darrkstarr** [ZeroXNoxus/dark-mode-5e#14]
Colors are inverted when editing spells, and effects in the Automated Animations module.
![Capture](https://github.com/ZeroXNoxus/dark-mode-5e/assets/159729381/f06a1818-d15d-4ff1-b267-b237d28c1067)

**Comment by ZeroXNoxus** [comment]
Fixed in next release, thanks for your contribution!
