### ISSUE TITLE
Journal Side Bar unreadable

### ISSUE THREAD

**Issue by BokuNC** [ZeroXNoxus/dark-mode-5e#15]
**Describe the bug**
As it is, this module adds a filter to invert colors pretty much everywhere on foundry. While the sheets do work flawlesly, it also changes colors in the menus and everywhere else, in a not so controlled way. 

The pages inside the Journal work flawlessly, but the side tab, where you select them by titles is dark blue on transparent dark grey, almost unreadable.

**To Reproduce**
1. Go to Journal Tab, create a new Journal and add a page with some title;
2. See error

**Expected behavior**
As it inverts the colors from the text inside the pages, i would assume it would also consider readability by using some contrast filter or something. At least change the text and color of the icons on that side bar to be clearer.

**Game Specifics:**
 - Game System and version: D&D 3.0.2
 - Module Version 2.0.4

**Comment by ZeroXNoxus** [comment]
Fixed in next release, thanks for your contribution!
