### ISSUE TITLE
Normal Colors on the Image Browser

### ISSUE THREAD

**Issue by jlawrence11** [ZeroXNoxus/dark-mode-5e#16]
**Is your feature request related to a problem? Please describe.**
The colors on the image browser are inverted, making it difficult to preview them before selecting them. Colors aren't inverted in other places.

**Describe the solution you'd like**
An exception being made to inverting the colors on the 'filepicker-body' class, or similar.

**Describe alternatives you've considered**
I'm new to foundry, I'm definitely open to something I may have missed, or a way that I can solve it myself.

**Additional context**
![Screenshot from 2024-02-16 16-43-26](https://github.com/ZeroXNoxus/dark-mode-5e/assets/4178771/6a8a353b-6ecd-4fd6-85e4-bf5d296a607a)

**Comment by ZeroXNoxus** [comment]
Hey, thanks for letting me know about this, but I have already fixed this issue. The next release will resolve the Problem.
