### ISSUE TITLE
Chat changes reverted in latest release.

### ISSUE THREAD

**Issue by ChthonicKnight** [ZeroXNoxus/dark-mode-5e#17]
Sorry for the spam in advance! Had it disabled and going back through to find some more bugs.

**Describe the bug**
Chat changes reverted in latest release.

Rolled back the code and seems the chat is working correctly.
![303735581-52a5b08f-0985-4e18-8d89-d0af4a2f4bea](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/1a3cd609-2212-414e-acdb-60153eaee5ea)

Current Version 2.0.4:
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/57e22fb9-9a95-494d-b485-583df6d2eaca)

**Game Specifics (please complete the following information):**
 - Game System and version: dnd5e 2.4.1
 - Foundry v11.315

**Comment by ZeroXNoxus** [comment]
Before opening a million issues please Update to the latest Version as multiple issues have Just been resolved in the 2.0.7 Release i published 2 hours ago

**Comment by ChthonicKnight** [comment]
Yes sorry I closed out some that I found out that you just made another update.

**Comment by ChthonicKnight** [comment]
Tested this on 2.0.7
Still the same

**Comment by ZeroXNoxus** [comment]
Tested on DnD 5th Ed. 2.4.1 + Module ver. 2.0.7:
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/29397572/8db6aedc-501a-4a70-8634-8ff818dd60a4)

I can not find an issue with Character Monitor.
What exactly should it look like in your opinion?

**Comment by ChthonicKnight** [comment]
This is how it looked before
![305751880-1a3cd609-2212-414e-acdb-60153eaee5ea](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/caf52376-a709-4096-9eb6-7c89fa538ae3)

**Comment by ZeroXNoxus** [comment]
Fixed in next release.
