### ISSUE TITLE
[Compatability] Monk's Enhanced Journal showing negative

### ISSUE THREAD

**Issue by ChthonicKnight** [ZeroXNoxus/dark-mode-5e#21]
**Describe the bug**
[Compatability] Monk's Enhanced Journal showing negative
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/4306f483-9999-4171-a0d5-7b9444ebd05d)

**Game Specifics (please complete the following information):**
 - Game System and version: dnd5e 2.4.1
 - Foundry v11.315

**Comment by ZeroXNoxus** [comment]
Interesting Issue. Do you have any additional module that is styling Monk's Enhanced Journals? It looks like this for me:
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/29397572/5c24749d-7775-402b-b842-57f1773d55e2)

**Comment by ChthonicKnight** [comment]
Probably have to configure the settings in Monk's Enhanced Journal. Here is what I have set:
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/c05aba17-c977-454f-8b2d-569e6fe15043)

**Comment by ZeroXNoxus** [comment]
I suppose this is the way you want it to look?
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/29397572/cb1d9dc3-23b2-4383-b2b0-6053d3e1a503)

Mind you, this is tested on DnD 5th Edition v3.0.2, so the transparent background could be caused by the newer version.

**Comment by ChthonicKnight** [comment]
That is close, this is how it looks without darkmode:
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/bf0230ef-9ccd-4fbc-9e4e-353ec4bffe41)

**Comment by ZeroXNoxus** [comment]
I'll work on this a bit more down the line, but the next release will be "close" enough :D

**Comment by ChthonicKnight** [comment]
Sounds good!

**Comment by MythicPalette** [comment]
I've also noticed that it inverts images in Monk's Enhanced Journal and IconPicker
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/67084868/410eb306-3f70-4b08-8fb9-901183b139b4)
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/67084868/975f3393-6d83-42ea-a638-60e964704992)
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/67084868/5a9bf5b4-000f-4281-a82a-559b1afdf40b)
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/67084868/e08ffb3c-1714-4ea0-a5cf-a4ebbdd9bc99)
