### ISSUE TITLE
[Combatability] Paperdoll showing negatvie again

### ISSUE THREAD

**Issue by ChthonicKnight** [ZeroXNoxus/dark-mode-5e#22]
**Describe the bug**
Paperdoll showing negatvie again
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/b03cf863-c166-4bba-a5be-7973762ef5c0)

**Game Specifics (please complete the following information):**
 - Game System and version: dnd5e 2.4.1
 - Foundry v11.315

**Comment by ZeroXNoxus** [comment]
Please confirm this is on the newest release of Dark Mode. I will exclude the styling I have made if this error occurs on the newest release. I can't confirm this fixed until you have tested it as I have no way of testing this.

**Comment by ChthonicKnight** [comment]
Confirmed this is happening on 2.0.7

**Comment by ZeroXNoxus** [comment]
Still happening on 2.0.8?

**Comment by ChthonicKnight** [comment]
Yeah still occurring on .8
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/93c2af35-0ff3-4c6f-9983-f5bfdbc5d3e7)

**Comment by ChthonicKnight** [comment]
If you want to DM me on discord I can send over a zip of the module folder. My username is the same there.

**Comment by ZeroXNoxus** [comment]
Alright, then the Same procedure as Last Time, I need a Screenshot of the console (F12), otherwise I sadly can't exclude my Styling from the Papier Doll module

**Comment by ZeroXNoxus** [comment]
Alright, what ist your Discord username?

**Comment by ChthonicKnight** [comment]
It is the same as here ChobitsCrazy

**Comment by ChthonicKnight** [comment]
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/836c9f7a-daf0-4aa6-85fc-1ae9c8ae6c8b)
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/51cb1339-243e-4865-af8f-464ae3f896d1)
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/f7ce681d-e680-48d6-be9a-f2c69ac9a12b)
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/d6e465a9-ca6a-4858-a84d-9266358ec87b)
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/53fc4f18-d373-487b-a2b0-45c29a03de51)
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/e0918740-a74c-436d-80de-76796dcbecf6)
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/dc4db138-4b16-4aa7-bd39-52bd24e4bd49)
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/79439937-7110-43bd-85d1-3719142d699c)
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/650cd0fc-fbf4-4a37-a535-3cc4a9f84bdb)
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/2a874205-1b20-465c-8d3f-f4de6d529131)
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/c5c0c462-f604-4272-8c0c-b0f8658f6ff7)
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/6fd72311-69a5-46a4-a446-7b65c03d5e6e)
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/b50e5c59-1c0d-4c52-be55-1fce0ca16214)

**Comment by ZeroXNoxus** [comment]
I have made a wild guess in the last release, could you kindly check if the issue was resolved with 2.0.9?
