### ISSUE TITLE
Bug: Compendium Entry text unreadable with dark mode enabled

### ISSUE THREAD

**Issue by DarcClan** [ZeroXNoxus/dark-mode-5e#23]
When Dark mode is enabled you cannot easily read the items/text in a compendium

1. Disable dark mode
2. Open a compendium
3. Enable dark mode

Screenshot
https://imgur.com/a/X3rnidw

**Comment by ZeroXNoxus** [comment]
You are liekly not on the newest release of the Dark Mode module (2.0.8). Please make sure you update your module to the newest release before opening an issue.
Cheers.

**Comment by DarcClan** [comment]
my apologies, I was still on 2.0.3, running 2.0.8 fixed it
