### ISSUE TITLE
[Compatability] Monk's Little Details, compendium context menu is transparent.

### ISSUE THREAD

**Issue by ChthonicKnight** [ZeroXNoxus/dark-mode-5e#24]
**Describe the bug**
Monk's Little Details, compendium context menu is transparent.

**To Reproduce**
With Dark Mode enabled and Monk's Little Details enabled right-click one of the compendiums:
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/255fb7f4-2869-4b59-ad5c-59c3de4d01bd)

**Expected behavior**
Should show with a normal background.

**Game Specifics (please complete the following information):**
 - Game System and version: DnD5e 2.4.1
 - Module Version: 2.0.8
 - Foundry v11.315

**Comment by ZeroXNoxus** [comment]
Will be fixed in next release!
