### ISSUE TITLE
Final charge promt showing poorly

### ISSUE THREAD

**Issue by ChthonicKnight** [ZeroXNoxus/dark-mode-5e#25]
**Describe the bug**
Final charge prompt showing poorly

**To Reproduce**
Create an item with a single charge that destroys on use. Ex Acid Vial
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/d83b7706-1708-410f-ba20-15d5e7e0566e)

Use the item and the prompt shows that it will destroy the item and the colors are strange.
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/1991c563-3f72-40f4-90f7-ca97821dadd3)

**Expected behavior**
Should show clearly

**Game Specifics (please complete the following information):**
    Game System and version: DnD5e 2.4.1
    Module Version: 2.0.8
    Foundry v11.315

**Comment by ZeroXNoxus** [comment]
Fixed in next release
