### ISSUE TITLE
Active Effect Icon showing negative

### ISSUE THREAD

**Issue by ChthonicKnight** [ZeroXNoxus/dark-mode-5e#26]
**Describe the bug**
Active Effect Icon showing negative

**To Reproduce**
Open any item
Click to the effects tab
Create an effect and edit it
Icon shows negative
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/ae2bec1e-85b6-4ddf-bbf4-82816562e3b7)

**Expected behavior**
Icon should be regular

**Game Specifics (please complete the following information):**
Game System and version: DnD5e 2.4.1
Module Version: 2.0.9
Foundry v11.315

**Comment by ZeroXNoxus** [comment]
Fixed in next release.
