### ISSUE TITLE
[Compatablity] Filepicker+ Showing negative

### ISSUE THREAD

**Issue by ChthonicKnight** [ZeroXNoxus/dark-mode-5e#27]
**Describe the bug**
Filepicker+ Showing negative

**To Reproduce**
With filepicker+ module enabled open the file browser:
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/89e54bce-d251-43aa-a797-203b7bdf01ff)

**Expected behavior**
Should be black as normal

**Game Specifics (please complete the following information):**
Game System and version: DnD5e 2.4.1
Module Version: 2.0.9
Foundry v11.315

**Comment by ChthonicKnight** [comment]
This is another premium module, I'll offer the elements:
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/06dfe38e-2395-4c89-a8b8-4b02bbc68d86)
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/8f5bf121-37e8-4589-ba27-9fb55eb918b6)
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/eb9b077d-0f8f-4613-b2e4-835b7b67075a)

**Comment by ZeroXNoxus** [comment]
The screenshots you have send to me are sadly not useful for me. Please provide screenshots like this:
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/29397572/900950a1-6911-4886-a7d5-be342796bbe6)

I need to be able to see the "class='XXX'" declarations for the filepicker. The same applies to Paper Doll.
