### ISSUE TITLE
[Compatability] Monk's Little Details + DF Quality of Life folder context menu blacked out

### ISSUE THREAD

**Issue by ChthonicKnight** [ZeroXNoxus/dark-mode-5e#28]
**Describe the bug**
Monk's Little Details + DF Quality of Life folder context menu blacked out

**To Reproduce**
Enable both Monk's Little Details and DF Quality of Life modules.
With dark mode enabled right-click any folder on the right menu i.e. Compendium/Item
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/0d6c806a-e020-41d5-9d7c-f37c58ce2fc4)

**Expected behavior**
Should show words correctly

**Game Specifics (please complete the following information):**
Game System and version: DnD5e 2.4.1
Module Version: 2.0.9
Foundry v11.315

**Comment by ZeroXNoxus** [comment]
I'll hand this issue over to DF as this is an issue caused by a bad styling decision from DF.

**Comment by ZeroXNoxus** [comment]
I will not solve this issue as DF Quality of Life is no longer being maintained and will liekly break in the future.

Bad styling decisions have been made which cause this issue.
