### ISSUE TITLE
[Combatability] Always HP

### ISSUE THREAD

**Issue by MustBeAlive** [ZeroXNoxus/dark-mode-5e#30]
Health Bar is negative and for some reason shifts to the bottom of the UI.

- Darkmode disabled:
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/125880043/8c1afceb-92fc-45cd-b796-07368dafffbf)
- Darkmode enabled:
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/125880043/c3fc9dbd-f930-47c7-bcc0-6f42e09ccdbb)

**Specifics**
 - Foundry V11.315
 - Game system: dnd5e 2.4.1
 - Darkmode: 2.0.9
 - Always HP: 11.07

**Comment by ZeroXNoxus** [comment]
Fixed in next release. Cheers!
