### ISSUE TITLE
[Compatability] Monk's Token Bar

### ISSUE THREAD

**Issue by MustBeAlive** [ZeroXNoxus/dark-mode-5e#31]
Token icons in both request roll and contested roll windows are negative. Upon completing the request, icons are also negative in the chat card.

![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/125880043/92daacee-6927-4049-b2db-d73680471663)
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/125880043/adea25f7-1c1e-4f1a-9bef-c306d822527f)
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/125880043/c23c1f85-c85c-4e81-a79e-eace23a81e91)
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/125880043/d5f01607-021a-4e92-801f-61aba24a9570)

**Specifics**
 - Foundry V11.315
 - Game system: dnd5e 2.4.1
 - Darkmode: 2.0.9
 - Monk's TokenBar: 11.14

**Comment by ZeroXNoxus** [comment]
Should be fixed in the next release. Cheers!
