### ISSUE TITLE
Change in some Colors

### ISSUE THREAD

**Issue by Liviu50** [ZeroXNoxus/dark-mode-5e#32]
So i took a look in the module and i love it but i would like to perhaps request some options to change some of the colors used?
Cause i found an issue:
If you, as a GM, modify the HP of someone and you have the monitor telling you that "X has modified HP" the highlight of the name basically becomes a neon color almost impossible to read.
Either maybe some adjustment or some options to modify slightly the colors of the theme itself? :) just a thought tho, this thing looks great for the most part so cheer!

**Comment by ZeroXNoxus** [comment]
> If you, as a GM, modify the HP of someone and you have the monitor telling you that "X has modified HP" the highlight of the name basically becomes a neon color almost impossible to read.

What monitor? is this a module? I can't replicate anything without more information. Please provide a module/setting name and a screenshot, otherwise I can not do anything with the information you have provided.

**Comment by Liviu50** [comment]
oh sorry, altho the module is called that yes.
Health Monitor and D&D5e Character Monitor are the two modules that might be giving me that message.
Basically install them and then simply modify the HP of any NPC and it should appear in chat that you modified character X HP or similar.
Since this module, from what i saw more or less, makes negative of most colors, that one becomes neon white.
Also another problem....images uploaded become also negative....that should be avoided cause it looks like a horror movie :D especially if you prepared a doc with a phanteon and the images of the gods there....(simply create a journal and drag and drop an image there...
still ill upload images to showcase, that should make it  easier ^^
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/96814785/d6ed1e0e-f87b-4796-b7ed-a11a1d21fbf9)
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/96814785/d44b7bd6-71c6-489b-b189-774b50535d0b)

**Comment by ZeroXNoxus** [comment]
Thank you for the clarification. I'll take a look into this when I have the time!

**Comment by ZeroXNoxus** [comment]
So, I have changed the image in the Journal, which should now display the non-inverted colors (will be out with the next release of Dark Mode).

However, the issue with the styling of the Health Monitor seems to be an issue which requires changes to the Health Monitor module itself for DnD 5th Edition v3.0.X, as the styling of their chat cards is not in my ball-park. Please open an issue there so this can be fixed. Cheers!

**Comment by Liviu50** [comment]
Hey man thx a lot for the fast response and modifications ^^ appreciate your work!
