### ISSUE TITLE
[Compatibility] Sequencer's Database Viewer is previewing negative footage

### ISSUE THREAD

**Issue by Tookie03** [ZeroXNoxus/dark-mode-5e#33]
https://github.com/ZeroXNoxus/dark-mode-5e/assets/107572957/6a283027-8db2-4fa5-97e4-11bec51dd84d

https://github.com/ZeroXNoxus/dark-mode-5e/assets/107572957/88b5ddff-6fed-4df3-bd62-493d2928a02f

**Comment by ZeroXNoxus** [comment]
Fixed in next release
