### ISSUE TITLE
Icons are forced to shrink when enabled

### ISSUE THREAD

**Issue by Ashen2724** [ZeroXNoxus/dark-mode-5e#34]
**Changes Size of Icons**
When I enable the module, the icons for selecting Journals/Actors shrink down. Making it a bit hard to see them compared to normally. This happened even before enabling dark mode on 

**To Reproduce**
1. Go to enable module, in module settings.
2. Click on Icons from Combat encounters (with actors on) to Settings.
3. Scroll down and click on some to see size difference from before and after.
4. There are no options for changing icons from what I've read or found, it's not a feature from what I read from module.

**Expected behavior**
I expected for Icons to stay the same size, this happens only when enabling the module. Not from enabling dark mode in settings.

**Screenshots**
![Before](https://github.com/ZeroXNoxus/dark-mode-5e/assets/161164707/3c8371a4-c801-46fe-94ad-0369dfd2483d)
![After](https://github.com/ZeroXNoxus/dark-mode-5e/assets/161164707/81b55e96-103a-42c3-a042-42ab726dd4bb)

**Game Specifics (please complete the following information):**
 - Game System and version: [dnd5e 3.0.3]
 - Module Version [2.1.0]
 - Foundry Version 11, Build 315
 - Hosted on Molten Server

**Comment by ZeroXNoxus** [comment]
Hello, thank you for the report, but I have intentionally included this change to make the scenes, actors, etc less cluttered in the right sidebar.

I will eventually migrate these changes to another Module, however this ist not in my To-Do list right now

**Comment by Ashen2724** [comment]
Thank you for explaining.
