### ISSUE TITLE
Journal images getting colors inverted

### ISSUE THREAD

**Issue by Mudartastisch** [ZeroXNoxus/dark-mode-5e#35]
**Describe the bug**
Adding any image to a journal entry inverts the colors.

**To Reproduce**
1. Go to 'Journal'
2. Create a Journal
3. Add a page with type image
4. add any image to it
5. See problem

**Expected behavior**
Images in journals should be excluded from the modification

**Screenshots**
![Foundry_Virtual_Tabletop_mfutsnG0Ot](https://github.com/ZeroXNoxus/dark-mode-5e/assets/8214824/8e505be2-be5e-4fe1-a10a-4a50452baf56)
Original image on the left, journal entry on the right

**Game Specifics (please complete the following information):**
 - Game System and version: [e.g. dnd5e 3.0.4]
 - Module Version [e.g. 2.1.0]

**Comment by ZeroXNoxus** [comment]
Fixed in next release, thanks for the notice!
