### ISSUE TITLE
[Compatablity] Build-A-Bonus's sheet becomes too dark

### ISSUE THREAD

**Issue by Tookie03** [ZeroXNoxus/dark-mode-5e#36]
Build-A-Bonus has a darker sheet for some reason, and causes dark mode to be unreadable.

[Without Dark Mode]
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/107572957/99c3cf65-55f9-468a-97b3-50cb0628ca34)

[With Dark Mode]
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/107572957/afc8e062-3ac4-4b16-8f5d-9a0fba418563)

**Comment by ZeroXNoxus** [comment]
This issue seems to have resolved itself with DnD 5th Edition 3.1.X and the current version of Dark Mode!
