### ISSUE TITLE
Spell Slots Displaying Always Consumed

### ISSUE THREAD

**Issue by CaptainRoBear** [ZeroXNoxus/dark-mode-5e#39]
Spell Slots on the Tidy 5e character sheet are only displaying consumed unless hovered over by the mouse pointer. The current bug makes it difficult to see what spell slots are available at a glance.

![Spell Slot view - hovered over available](https://github.com/user-attachments/assets/69cd1d7c-d4b4-4072-b41c-44b4b42888c4)
![Spell Slot view - hovered over consumed](https://github.com/user-attachments/assets/736b1f87-ba68-43f2-9726-7296ce1c6f6c)
![Spell Slot view](https://github.com/user-attachments/assets/36d29b53-eab6-4ac4-ad14-21778b0cc670)

**Comment by ZeroXNoxus** [comment]
Hey @CaptainRoBear thanks for the bug report. Have you already tried the current version of Dark Mode for 5e? The current version has fixed this issue. Can you check if you have version 2.3.2 installed? Thank you in advance!
