### ISSUE TITLE
[dnd5e 2.4.0] Advancement options & features difficult to read

### ISSUE THREAD

**Issue by etiquettestartshere** [ZeroXNoxus/dark-mode-5e#4]
Advancement options and feature names on the Advancement interface are difficult to read, as they don't seem to update with the theme. 

Included is a full screenshot of the Dragonborn SRD race item's advancement interface in the dark mode theme, along with how an example advancement option looks in the Advancement interface in the black and white and programmer themes.

![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/148253744/c736f1c4-f1f4-4639-93b1-53ba62f6af61)
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/148253744/efbba1f0-6390-4539-9c9b-7392085a45f2)
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/148253744/4462acbb-1c5a-40c4-bc7d-a83a5cfb8e1f)

**Comment by ZeroXNoxus** [comment]
Thanks for letting me know! This will be fixed in the next release.
