### ISSUE TITLE
Compatiblity with Monk's Enhanced Journals

### ISSUE THREAD

**Issue by ChthonicKnight** [ZeroXNoxus/dark-mode-5e#6]
Monk's enhanced journal adds a few new pages that you can add for journals:
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/b8e5a2ea-e032-4696-9738-b348138b7ec1)

For these there seems to end up with black on black text. Example for a place:
Normal:
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/c58558f6-d8d9-47b5-8299-1ba7ea6f812b)

Dark Mode:
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/8379f658-ac53-4f11-a1e7-48dab4d1f2a0)

Also as a side note similar to what you did for Tidy 5e sheets I would like to exclude the Plutonium module from getting updated by Dark Mode.

Thank you for the hard work!

**Comment by ZeroXNoxus** [comment]
Thank you for using "Dark Mode for 5e"! I'll get onto this asap, but I need to take the new character sheets and overall stylings of DnD 3.0.x into consideration and fix some issues I have created while not understanding the way Foundry modules can be written.

I want to recreate the module and need some time to get the code together, while also cleaning the CSS. I'll get back to this as soon as I have made these changes. Cheers!

**Comment by fluxxdog** [comment]
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/12112509/14701c8d-ee30-41e4-ac64-00d0e57062f7)
With 2.0.0, the text is readable, so definitely a move in the right direction. The side bar is supposed to have "Aded Vale" highlighted in green and "Rulings" and "Mountain Throne" in red. Looks like the sidebar got inverted colorwise. Still very readable though.

**Comment by ZeroXNoxus** [comment]
Thanks for the heads Up! I haven't had time yet to work on this. I'll get a setup ready for the next release which will include a more thoughtful rework for the Monk's Enhanced Journals. Good to know, though, that the new Dark Mode seems to work in most cases!

**Comment by ZeroXNoxus** [comment]
Should be fixed now as follows:

![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/29397572/690a3f8e-8e79-4674-9dee-38bf24f1bc59)

The fix is included in the 2.0.1 release. Cheers!
