### ISSUE TITLE
dnd5e v3.0.1 Issue with Components Styled

### ISSUE THREAD

**Issue by GCSmith-07** [ZeroXNoxus/dark-mode-5e#7]
Some of the components are visible and others are not with the styling in the new system version:
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/100705086/dc0a2181-d00c-49ac-864e-ba6fe7b48efc)

VS Light Mode (for ref):
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/100705086/0c0a0c26-86aa-4243-bfa7-15d910b8a735)

**Comment by ZeroXNoxus** [comment]
I am aware of this issue. Please disabled dark mode for now, I already have a solution in mind.

**Comment by GCSmith-07** [comment]
Will do. Just wanted to let you know since your module has saved my eyes countless times :)

**Comment by ZeroXNoxus** [comment]
Thanks for the praise! I'm grateful that some people use my modules at all and am happy you appreciate the effort that goes into these modules.

I'm happy to anounce that a new release is underway, in about 5 minutes it should be available to download! Thanks again for your support! Have a nice day.

**Comment by GCSmith-07** [comment]
Thanks for your all your effort, update looks great! Development definitely is not an easy process sometimes, keep up the good work!
