### ISSUE TITLE
Dark Mode affects Small Time graphics [2.0.1]

### ISSUE THREAD

**Issue by fluxxdog** [ZeroXNoxus/dark-mode-5e#8]
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/12112509/2d956892-ad4f-4bb6-ada5-81db19c1377b)
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/12112509/26c6993f-a9dc-4fbe-966b-9f56bab3020f)
Dark Mode inverted the colors for this module with 2.0.1. (Not gonna lie, the blood red sky with a blue sun is kinda cool looking.)

**Comment by ZeroXNoxus** [comment]
Fixed in next release, thanks for your contribution!

**Comment by fluxxdog** [comment]
Glad I could help.

Need to reopen this one unfortunately. The settings page is still affected.

**Comment by ZeroXNoxus** [comment]
Ah, sorry, I have never used this module before. I'll look into this right away

**Comment by ZeroXNoxus** [comment]
Finished in next release:
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/29397572/b597f97f-5d6a-43a9-96dd-34f947809a1c)
