### ISSUE TITLE
Conflict with Paper Doll Module

### ISSUE THREAD

**Issue by ChthonicKnight** [ZeroXNoxus/dark-mode-5e#9]
Conflict with Paper Doll Module
Icons get distorted and there is a white hue.
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/a3c69a39-57e5-4e8a-af31-613840a6806f)

**Comment by ZeroXNoxus** [comment]
Thanks for letting me know about this issue, however this module is exclusive content, so I can not modify this without buying this module. Please provide sheet inspection of the openend window so I can help with this issue, otherwise disable until further notice!

**Comment by ChthonicKnight** [comment]
How can I provide the sheet inspection?

**Comment by ZeroXNoxus** [comment]
- Go into your code inspector for your web browser (Chrome -> F12; Opera GX -> CTRL + SHIFT + C)
- use the element selector (Chrome -> CTRL + SHIFT + C; Opera GX -> Automatically selected) Alternatively, click the "Code Selector" Icon in the top-left corner of the now opened window.
- Hover over the opened character sheet, you should see a blue box over the hovered element
- once you have the biggest element you can find selected, simply lef click
- You should now see something like this:
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/29397572/917a6b51-9a09-45e7-a849-4fa8b5621abe)

- send me the screenshot akin to the one I have sent above. Please send me the full window so I can see all of the elements.

**Comment by ChthonicKnight** [comment]
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/ed3e83ff-cc80-44e5-9a46-150bdde7c216)
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/738ad5d9-1f98-4cda-a40a-fbd7809bbf49)
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/6547e545-c149-4656-9c5f-7ba2338bfccd)
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/d8323651-5c73-4a94-b64e-0c50d2c5e544)
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/8ee7e22b-3717-4f8c-bf9c-33456ad739be)
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/591bb775-9e8a-4ec1-9c06-a6eb6fa1e709)

**Comment by ZeroXNoxus** [comment]
Thanks you very much, this is really helpful.

**Comment by ZeroXNoxus** [comment]
Can you check the Paperdoll Screen again for me? I included a styling as a guess and it seems I nailed the ID of the Paperdoll Sheet.
If not, I'll look further into this.

**Comment by ChthonicKnight** [comment]
Looks good! Issue resolved on latest code.
